# [your info]
email: 'xiangchen@acm.org'

# [your team]
urlGames: 'https://seatgeek.com/pittsburgh-penguins-tickets'
# use the team's name (replace space if there's any with '-'') 
# to indicate location, e.g., 'penguins' means at pittsburgh
locGames: 'penguins'

# [interval between two consective scrapes]
# = fixed + random(0, 1) * flexible
fixedInterval: 50000 # 50 sec
flexibleInterval: 150000 # 150 sec

# [filtering criteria]
# - OR between entries
# - AND within each entry
# e.g., the following means scraping ticket deals that satisfy
# (score>=97) OR (score>=88 AND maxPrice<$30 AND year==2017)
filters:
  - score: 97
  - score: 88
    maxPrice: 30
    year: 2017